### ISSUE TITLE
User IP adress is not correctly retrieved if Load balancer is used…

### ISSUE THREAD

**Issue by dgillier** [Label84/laravel-auth-log#2]
Hello,

If a load balancer is used, this package is retrieving the load balancer address and not the user one.

Did not find a config option or something similar, am'I wrong ?

Thanks,
Denis

**Comment by tjardoo** [comment]
Did you add the IP of your load balancer to the trusted proxies in Laravel? In that case Laravel will read some HTTP-headers to know about the end-user making the request (incl. their IP). Then this issue should resolve itself. Let me know.

**Comment by dgillier** [comment]
Thanks for your answer !
Yes I'm using now the TrustProxies middleware and it's working :)
