### ISSUE TITLE
Custom Events and Listeners not being loaded

### ISSUE THREAD

**Issue by bulentsakarya** [Label84/laravel-auth-log#3]
The package prevents automatic recognition of Events and Listeners that come with Laravel 11. However, I can use my own Events and Listeners by defining them within the AppServiceProvider.

**Comment by tjardoo** [comment]
@bulentsakarya I tried to replicate this but I don't have any issue getting the events automatically recognized. When you remove this package it does automatically recognize the Events and Listeners - and when you add this package it does not anymore?

[https://laravel.com/docs/11.x/events#event-discovery](https://laravel.com/docs/11.x/events#event-discovery)

**Comment by tjardoo** [comment]
Thanks! I can replicate the issue with a new Laravel 11 application. After creating a test Event and test Listener - running `php artisan event:list` recognizes the test event. But after adding the package the auth events are recognized but the test Event is not anymore.
